on:
  push:
    branches:
      - master
      - dev

jobs:
    Workflow:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Compiling contracts
          run: make compile
        - name: LIGO testing for contracts
          run: make test-ligo
        - name: Python testing for contracts
          run: make test-python